# https://cloud.google.com/build/docs/configuring-builds/create-basic-configuration
# steps to create a cloudbuild.yaml configuration
# 1. create cloudbuild.yaml
# 2. add steps - build steps for cloud build to perform
#   2a. first step - "name" to point to a container image
#   2b. add arguments step - "args" - arguments to be passed to the builder
# 3. more steps as required
# 4. additional build configuration fields
# end it with a timeout declaration
steps:
# https://cloud.google.com/build/docs/cloud-builders
- name: 'python'
  entrypoint: 'bash'
  args:
  - '-c'
  - |
    pip install pytest
    pytest
- name: 'gcr.io/cloud-builders/gcloud'
  args:
  - 'app'
  - 'deploy'
  
options:
  logging: CLOUD_LOGGING_ONLY

timeout: 1600s